//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;
using NotNullAttribute = System.Diagnostics.CodeAnalysis.NotNullAttribute;

namespace Tomoryo
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<ImportProducts>();
            }
        }
    }
    public partial class ImportProducts
    {
        [NotNull]
        public String Product { get; set; }
        
        [NotNull]
        public Decimal Price { get; set; }
        
        [NotNull]
        public String Description { get; set; }
        
        [NotNull]
        public Int64 Quantity { get; set; }
        
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [NotNull]
        public String Category { get; set; }
        
    }
    
}
